/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author JULIAN
 */
public class contruccion_de_platos extends javax.swing.JFrame {

    /**
     * Creates new form contruccion_de_platos
     */
    public contruccion_de_platos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        btn_crearplato = new javax.swing.JButton();
        btn_agregar_ing = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_receta = new javax.swing.JButton();
        btn_asignar_platos = new javax.swing.JButton();
        btn_crear_carta = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encar.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        TITULO.setBackground(new java.awt.Color(51, 51, 255));
        TITULO.setForeground(new java.awt.Color(51, 51, 255));
        TITULO.setText("BIENVENIDO ENCARGADO POR FAVOR ESCOJA UNA OPCIÓN:");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 37, -1, -1));

        btn_crearplato.setText("CREAR PLATO");
        getContentPane().add(btn_crearplato, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 119, -1, -1));

        btn_agregar_ing.setText("AGREGAR NUEVO INGREDIENTE");
        getContentPane().add(btn_agregar_ing, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        btn_receta.setText("AGREGAR RECETA");
        btn_receta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recetaActionPerformed(evt);
            }
        });

        btn_asignar_platos.setText("ASIGNAR PLATOS A LA CARTA");

        btn_crear_carta.setText("CREAR CARTA");

        btn_Cerrar.setText("Cerrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(btn_crear_carta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_asignar_platos)
                    .addComponent(btn_receta))
                .addGap(232, 232, 232))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Cerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(btn_receta)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_asignar_platos)
                    .addComponent(btn_crear_carta))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_recetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_recetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contruccion_de_platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contruccion_de_platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contruccion_de_platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contruccion_de_platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contruccion_de_platos().setVisible(true);
            }
        });
    }

    public JLabel getFONDO() {
        return FONDO;
    }

    public void setFONDO(JLabel FONDO) {
        this.FONDO = FONDO;
    }

    public JLabel getTITULO() {
        return TITULO;
    }

    public void setTITULO(JLabel TITULO) {
        this.TITULO = TITULO;
    }

    public JButton getBtn_agregar_ing() {
        return btn_agregar_ing;
    }

    public void setBtn_agregar_ing(JButton btn_agregar_ing) {
        this.btn_agregar_ing = btn_agregar_ing;
    }

    public JButton getBtn_crearplato() {
        return btn_crearplato;
    }

    public void setBtn_crearplato(JButton btn_crearplato) {
        this.btn_crearplato = btn_crearplato;
    }

    public JButton getBtn_receta() {
        return btn_receta;
    }

    public void setBtn_receta(JButton btn_receta) {
        this.btn_receta = btn_receta;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JButton getBtn_Cerrar() {
        return btn_Cerrar;
    }

    public void setBtn_Cerrar(JButton btn_Cerrar) {
        this.btn_Cerrar = btn_Cerrar;
    }

    public JButton getBtn_asignar_platos() {
        return btn_asignar_platos;
    }

    public void setBtn_asignar_platos(JButton btn_asignar_platos) {
        this.btn_asignar_platos = btn_asignar_platos;
    }

    public JButton getBtn_crear_carta() {
        return btn_crear_carta;
    }

    public void setBtn_crear_carta(JButton btn_crear_carta) {
        this.btn_crear_carta = btn_crear_carta;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_agregar_ing;
    private javax.swing.JButton btn_asignar_platos;
    private javax.swing.JButton btn_crear_carta;
    private javax.swing.JButton btn_crearplato;
    private javax.swing.JButton btn_receta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
