/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author JULIAN
 */
public class Form_Plato extends javax.swing.JFrame {

    /**
     * Creates new form Plato
     */
    public Form_Plato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        FONDO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_foto = new javax.swing.JLabel();
        lb_precio = new javax.swing.JLabel();
        lb_describpcion = new javax.swing.JLabel();
        lb_comple = new javax.swing.JLabel();
        lb_cat = new javax.swing.JLabel();
        lb_regi = new javax.swing.JLabel();
        comb_compl = new javax.swing.JComboBox<>();
        com_cat = new javax.swing.JComboBox<>();
        comb_reg = new javax.swing.JComboBox<>();
        txt_id = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_des = new javax.swing.JTextField();
        txt_foto = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_registrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_carta = new javax.swing.JTextArea();
        lb_carta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area_receta = new javax.swing.JTextArea();
        lbl_Recetas = new javax.swing.JLabel();
        lbl_Cartas = new javax.swing.JLabel();
        txt_carta = new javax.swing.JTextField();
        txt_receta = new javax.swing.JTextField();
        Btn_cerrar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plato.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("PLATO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lbl_id.setText("Digite el ID del plato:");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        lb_nombre.setText("Digite el nombre del plato:");
        getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        lb_foto.setText("Foto:");
        getContentPane().add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        lb_precio.setText("Precio:");
        getContentPane().add(lb_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        lb_describpcion.setText("Descripción");
        getContentPane().add(lb_describpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        lb_comple.setText("Seleccione la complejidad");
        getContentPane().add(lb_comple, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        lb_cat.setText("Seleccione la categoria");
        getContentPane().add(lb_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        lb_regi.setText("Seleccione la region");
        getContentPane().add(lb_regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        comb_compl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil" }));
        comb_compl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_complActionPerformed(evt);
            }
        });
        getContentPane().add(comb_compl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        com_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desayuno", "Almuerzo", "Cena" }));
        getContentPane().add(com_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        comb_reg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andina", "Llanos", "Caribe", "Pacífica", "Amazonía" }));
        getContentPane().add(comb_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 60, -1));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 60, -1));
        getContentPane().add(txt_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, -1));
        getContentPane().add(txt_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 60, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 60, -1));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        btn_registrar.setText("REGISTRAR PLATO");

        txtarea_carta.setColumns(20);
        txtarea_carta.setRows(5);
        jScrollPane1.setViewportView(txtarea_carta);

        lb_carta.setText("Seleccione la Receta");

        jLabel3.setText("Digite la de Carta");

        txt_area_receta.setColumns(20);
        txt_area_receta.setRows(5);
        jScrollPane2.setViewportView(txt_area_receta);

        lbl_Recetas.setText("Recetas:");

        lbl_Cartas.setText("Cartas");

        Btn_cerrar.setText("Cerrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_carta)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addComponent(txt_carta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Cartas)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(txt_receta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Recetas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_registrar)
                                .addGap(40, 40, 40)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btn_cerrar)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Btn_cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_carta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Cartas))
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_carta)
                            .addComponent(lbl_Recetas)
                            .addComponent(txt_receta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_registrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comb_complActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_complActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_complActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Plato().setVisible(true);
            }
        });
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLbl_Cartas() {
        return lbl_Cartas;
    }

    public void setLbl_Cartas(JLabel lbl_Cartas) {
        this.lbl_Cartas = lbl_Cartas;
    }

    public JLabel getLbl_Recetas() {
        return lbl_Recetas;
    }

    public void setLbl_Recetas(JLabel lbl_Recetas) {
        this.lbl_Recetas = lbl_Recetas;
    }

    public JTextField getTxt_carta() {
        return txt_carta;
    }

    public void setTxt_carta(JTextField txt_carta) {
        this.txt_carta = txt_carta;
    }

    public JTextField getTxt_receta() {
        return txt_receta;
    }

    public void setTxt_receta(JTextField txt_receta) {
        this.txt_receta = txt_receta;
    }

    public JButton getBtn_cerrar() {
        return Btn_cerrar;
    }

    public void setBtn_cerrar(JButton Btn_cerrar) {
        this.Btn_cerrar = Btn_cerrar;
    }

    public JLabel getFONDO() {
        return FONDO;
    }

    public void setFONDO(JLabel FONDO) {
        this.FONDO = FONDO;
    }

    public JButton getBtn_registrar() {
        return btn_registrar;
    }

    public void setBtn_registrar(JButton btn_registrar) {
        this.btn_registrar = btn_registrar;
    }

    public JTextArea getTxt_area_receta() {
        return txt_area_receta;
    }

    public void setTxt_area_receta(JTextArea txt_area_receta) {
        this.txt_area_receta = txt_area_receta;
    }

    public JTextArea getTxtarea_carta() {
        return txtarea_carta;
    }

    public void setTxtarea_carta(JTextArea txtarea_carta) {
        this.txtarea_carta = txtarea_carta;
    }

    public JComboBox<String> getCom_cat() {
        return com_cat;
    }

    public void setCom_cat(JComboBox<String> com_cat) {
        this.com_cat = com_cat;
    }

    public JComboBox<String> getComb_compl() {
        return comb_compl;
    }

    public void setComb_compl(JComboBox<String> comb_compl) {
        this.comb_compl = comb_compl;
    }

    public JComboBox<String> getComb_reg() {
        return comb_reg;
    }

    public void setComb_reg(JComboBox<String> comb_reg) {
        this.comb_reg = comb_reg;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    public JLabel getLb_carta() {
        return lb_carta;
    }

    public void setLb_carta(JLabel lb_carta) {
        this.lb_carta = lb_carta;
    }

    public JLabel getLb_cat() {
        return lb_cat;
    }

    public void setLb_cat(JLabel lb_cat) {
        this.lb_cat = lb_cat;
    }

    public JLabel getLb_comple() {
        return lb_comple;
    }

    public void setLb_comple(JLabel lb_comple) {
        this.lb_comple = lb_comple;
    }

    public JLabel getLb_describpcion() {
        return lb_describpcion;
    }

    public void setLb_describpcion(JLabel lb_describpcion) {
        this.lb_describpcion = lb_describpcion;
    }

    public JLabel getLb_foto() {
        return lb_foto;
    }

    public void setLb_foto(JLabel lb_foto) {
        this.lb_foto = lb_foto;
    }

    public JLabel getLb_nombre() {
        return lb_nombre;
    }

    public void setLb_nombre(JLabel lb_nombre) {
        this.lb_nombre = lb_nombre;
    }

    public JLabel getLb_precio() {
        return lb_precio;
    }

    public void setLb_precio(JLabel lb_precio) {
        this.lb_precio = lb_precio;
    }

    public JLabel getLb_regi() {
        return lb_regi;
    }

    public void setLb_regi(JLabel lb_regi) {
        this.lb_regi = lb_regi;
    }

    public JLabel getLbl_id() {
        return lbl_id;
    }

    public void setLbl_id(JLabel lbl_id) {
        this.lbl_id = lbl_id;
    }

    public JTextField getTxt_des() {
        return txt_des;
    }

    public void setTxt_des(JTextField txt_des) {
        this.txt_des = txt_des;
    }

    public JTextField getTxt_foto() {
        return txt_foto;
    }

    public JTextArea getTxtarea_region() {
        return txtarea_carta;
    }

    public void setTxtarea_region(JTextArea txtarea_region) {
        this.txtarea_carta = txtarea_region;
    }

    public void setTxt_foto(JTextField txt_foto) {
        this.txt_foto = txt_foto;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nombre() {
        return txt_nombre;
    }

    public void setTxt_nombre(JTextField txt_nombre) {
        this.txt_nombre = txt_nombre;
    }

    public JTextField getTxt_precio() {
        return txt_precio;
    }

    public void setTxt_precio(JTextField txt_precio) {
        this.txt_precio = txt_precio;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JComboBox<String> com_cat;
    private javax.swing.JComboBox<String> comb_compl;
    private javax.swing.JComboBox<String> comb_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb_carta;
    private javax.swing.JLabel lb_cat;
    private javax.swing.JLabel lb_comple;
    private javax.swing.JLabel lb_describpcion;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JLabel lb_regi;
    private javax.swing.JLabel lbl_Cartas;
    private javax.swing.JLabel lbl_Recetas;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTextArea txt_area_receta;
    private javax.swing.JTextField txt_carta;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_foto;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_receta;
    private javax.swing.JTextArea txtarea_carta;
    // End of variables declaration//GEN-END:variables
}
