/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author JULIAN
 */
public class form_Ingrediente extends javax.swing.JFrame {

    /**
     * Creates new form Ingrediente
     */
    public form_Ingrediente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoingrediente = new javax.swing.JLabel();
        lblingrediente = new javax.swing.JLabel();
        lbidingr = new javax.swing.JLabel();
        lbidrece_ingre = new javax.swing.JLabel();
        lbnomingre = new javax.swing.JLabel();
        lblmedida_ingre = new javax.swing.JLabel();
        lb_cantidad_ingre = new javax.swing.JLabel();
        txtidingre = new javax.swing.JTextField();
        txtidrecete_ingre = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtmedida_ingre = new javax.swing.JTextField();
        txt_cantidad_ingre = new javax.swing.JTextField();
        btningrediente = new javax.swing.JButton();
        lbl_mostrar_recetas = new javax.swing.JLabel();
        comb_receta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoingrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingrediente.jpg"))); // NOI18N

        lblingrediente.setBackground(new java.awt.Color(204, 255, 0));
        lblingrediente.setForeground(new java.awt.Color(0, 102, 102));
        lblingrediente.setText("Ingredientes");

        lbidingr.setText("Digite el id del ingrediente:");

        lbidrece_ingre.setText("Digite el id de la receta:");

        lbnomingre.setText("Digite el nombre del ingrediente:");

        lblmedida_ingre.setText("Digite la medida del ingrediente: ");

        lb_cantidad_ingre.setText("Digite la cantidad:");

        btningrediente.setText("Registrar Ingrediente");

        lbl_mostrar_recetas.setText("Recetas disponibles:");

        comb_receta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbidingr)
                            .addComponent(lbidrece_ingre))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidrecete_ingre)
                            .addComponent(txtidingre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbnomingre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmedida_ingre)
                            .addComponent(lb_cantidad_ingre)
                            .addComponent(lbl_mostrar_recetas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comb_receta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_cantidad_ingre, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txtmedida_ingre))))
                .addGap(18, 18, 18)
                .addComponent(fondoingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblingrediente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btningrediente)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblingrediente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fondoingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbidingr)
                            .addComponent(txtidingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbidrece_ingre)
                            .addComponent(txtidrecete_ingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbnomingre)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmedida_ingre)
                            .addComponent(txtmedida_ingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_cantidad_ingre)
                            .addComponent(txt_cantidad_ingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_mostrar_recetas)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb_receta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addComponent(btningrediente)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_Ingrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_Ingrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_Ingrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_Ingrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_Ingrediente().setVisible(true);
            }
        });
    }

    public JComboBox<String> getComb_receta() {
        return comb_receta;
    }

    public void setComb_receta(JComboBox<String> comb_receta) {
        this.comb_receta = comb_receta;
    }

    public JButton getBtningrediente() {
        return btningrediente;
    }

    public void setBtningrediente(JButton btningrediente) {
        this.btningrediente = btningrediente;
    }

    public JLabel getFondoingrediente() {
        return fondoingrediente;
    }

    public void setFondoingrediente(JLabel fondoingrediente) {
        this.fondoingrediente = fondoingrediente;
    }
    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    public JLabel getLb_cantidad_ingre() {
        return lb_cantidad_ingre;
    }

    public void setLb_cantidad_ingre(JLabel lb_cantidad_ingre) {
        this.lb_cantidad_ingre = lb_cantidad_ingre;
    }

    public JLabel getLbidingr() {
        return lbidingr;
    }

    public void setLbidingr(JLabel lbidingr) {
        this.lbidingr = lbidingr;
    }

    public JLabel getLbidrece_ingre() {
        return lbidrece_ingre;
    }

    public void setLbidrece_ingre(JLabel lbidrece_ingre) {
        this.lbidrece_ingre = lbidrece_ingre;
    }

    public JLabel getLbl_mostrar_recetas() {
        return lbl_mostrar_recetas;
    }

    public void setLbl_mostrar_recetas(JLabel lbl_mostrar_recetas) {
        this.lbl_mostrar_recetas = lbl_mostrar_recetas;
    }

    public JLabel getLblingrediente() {
        return lblingrediente;
    }

    public void setLblingrediente(JLabel lblingrediente) {
        this.lblingrediente = lblingrediente;
    }

    public JLabel getLblmedida_ingre() {
        return lblmedida_ingre;
    }

    public void setLblmedida_ingre(JLabel lblmedida_ingre) {
        this.lblmedida_ingre = lblmedida_ingre;
    }

    public JLabel getLbnomingre() {
        return lbnomingre;
    }

    public void setLbnomingre(JLabel lbnomingre) {
        this.lbnomingre = lbnomingre;
    }

    public JTextField getTxt_cantidad_ingre() {
        return txt_cantidad_ingre;
    }

    public void setTxt_cantidad_ingre(JTextField txt_cantidad_ingre) {
        this.txt_cantidad_ingre = txt_cantidad_ingre;
    }

    public JTextField getTxtidingre() {
        return txtidingre;
    }

    public void setTxtidingre(JTextField txtidingre) {
        this.txtidingre = txtidingre;
    }

    public JTextField getTxtidrecete_ingre() {
        return txtidrecete_ingre;
    }

    public void setTxtidrecete_ingre(JTextField txtidrecete_ingre) {
        this.txtidrecete_ingre = txtidrecete_ingre;
    }

    public JTextField getTxtmedida_ingre() {
        return txtmedida_ingre;
    }

    public void setTxtmedida_ingre(JTextField txtmedida_ingre) {
        this.txtmedida_ingre = txtmedida_ingre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningrediente;
    private javax.swing.JComboBox<String> comb_receta;
    private javax.swing.JLabel fondoingrediente;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lb_cantidad_ingre;
    private javax.swing.JLabel lbidingr;
    private javax.swing.JLabel lbidrece_ingre;
    private javax.swing.JLabel lbl_mostrar_recetas;
    private javax.swing.JLabel lblingrediente;
    private javax.swing.JLabel lblmedida_ingre;
    private javax.swing.JLabel lbnomingre;
    private javax.swing.JTextField txt_cantidad_ingre;
    private javax.swing.JTextField txtidingre;
    private javax.swing.JTextField txtidrecete_ingre;
    private javax.swing.JTextField txtmedida_ingre;
    // End of variables declaration//GEN-END:variables
}
