/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author JULIAN
 */
public class form_admin_encargado extends javax.swing.JFrame {

    /**
     * Creates new form form_admin_encargado
     */
    public form_admin_encargado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombre_encargado = new javax.swing.JTextField();
        txt_id_encargado = new javax.swing.JTextField();
        btn_cerrar = new javax.swing.JButton();
        lbl_region = new javax.swing.JLabel();
        combox_region = new javax.swing.JComboBox<>();
        btn_regitraren = new javax.swing.JButton();
        btn_ventas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_ventas = new javax.swing.JLabel();
        lbln_nombre_encargado = new javax.swing.JLabel();
        lbl_id_encargado = new javax.swing.JLabel();
        fondo_admin_enc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ASINGAR ENCARGADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 55, -1, -1));
        getContentPane().add(txt_nombre_encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 78, 102, -1));
        getContentPane().add(txt_id_encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 52, 102, -1));

        btn_cerrar.setText("Cerrar");
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 11, -1, -1));

        lbl_region.setText("Region: ");
        getContentPane().add(lbl_region, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        combox_region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andina", "Llanos", "Caribe", "Pacífica", "Amazonía" }));
        getContentPane().add(combox_region, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 104, -1, -1));

        btn_regitraren.setText("Registrar Nuevo Encargado");
        getContentPane().add(btn_regitraren, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 150, -1, -1));

        btn_ventas.setText("Ventas");
        getContentPane().add(btn_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 296, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_ventas.setText("REVISAR VENTAS:");

        lbln_nombre_encargado.setText("Nombre de encargado:");

        lbl_id_encargado.setText("Id del encargado:");

        fondo_admin_enc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asginar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(lbl_ventas)
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo_admin_enc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id_encargado)
                    .addComponent(lbln_nombre_encargado))
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_id_encargado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbln_nombre_encargado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ventas)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fondo_admin_enc)
                        .addContainerGap(71, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_admin_encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_admin_encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_admin_encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_admin_encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_admin_encargado().setVisible(true);
            }
        });
    }

    public JButton getBtn_cerrar() {
        return btn_cerrar;
    }

    public void setBtn_cerrar(JButton btn_cerrar) {
        this.btn_cerrar = btn_cerrar;
    }

    public JButton getBtn_regitraren() {
        return btn_regitraren;
    }

    public void setBtn_regitraren(JButton btn_regitraren) {
        this.btn_regitraren = btn_regitraren;
    }

    public JButton getBtn_ventas() {
        return btn_ventas;
    }

    public void setBtn_ventas(JButton btn_ventas) {
        this.btn_ventas = btn_ventas;
    }

    public JComboBox<String> getCombox_region() {
        return combox_region;
    }

    public void setCombox_region(JComboBox<String> combox_region) {
        this.combox_region = combox_region;
    }

    public JLabel getFondo_admin_enc() {
        return fondo_admin_enc;
    }

    public void setFondo_admin_enc(JLabel fondo_admin_enc) {
        this.fondo_admin_enc = fondo_admin_enc;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getLbl_id_encargado() {
        return lbl_id_encargado;
    }

    public void setLbl_id_encargado(JLabel lbl_id_encargado) {
        this.lbl_id_encargado = lbl_id_encargado;
    }

    public JLabel getLbl_region() {
        return lbl_region;
    }

    public void setLbl_region(JLabel lbl_region) {
        this.lbl_region = lbl_region;
    }

    public JLabel getLbl_ventas() {
        return lbl_ventas;
    }

    public void setLbl_ventas(JLabel lbl_ventas) {
        this.lbl_ventas = lbl_ventas;
    }

    public JLabel getLbln_nombre_encargado() {
        return lbln_nombre_encargado;
    }

    public void setLbln_nombre_encargado(JLabel lbln_nombre_encargado) {
        this.lbln_nombre_encargado = lbln_nombre_encargado;
    }

    public JTextField getTxt_id_encargado() {
        return txt_id_encargado;
    }

    public void setTxt_id_encargado(JTextField txt_id_encargado) {
        this.txt_id_encargado = txt_id_encargado;
    }

    public JTextField getTxt_nombre_encargado() {
        return txt_nombre_encargado;
    }

    public void setTxt_nombre_encargado(JTextField txt_nombre_encargado) {
        this.txt_nombre_encargado = txt_nombre_encargado;
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_regitraren;
    private javax.swing.JButton btn_ventas;
    private javax.swing.JComboBox<String> combox_region;
    private javax.swing.JLabel fondo_admin_enc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_id_encargado;
    private javax.swing.JLabel lbl_region;
    private javax.swing.JLabel lbl_ventas;
    private javax.swing.JLabel lbln_nombre_encargado;
    private javax.swing.JTextField txt_id_encargado;
    private javax.swing.JTextField txt_nombre_encargado;
    // End of variables declaration//GEN-END:variables
}
