/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Facade;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.DTO.Administrador;

/**
 *
 * @author JULIAN
 */
public class login_administrador extends javax.swing.JFrame {

    /**
     * Creates new form login_administrador
     */
    public login_administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_id_admin = new javax.swing.JLabel();
        lb_nombre_admin = new javax.swing.JLabel();
        txt_id_admin = new javax.swing.JTextField();
        txt_nombre_admin = new javax.swing.JTextField();
        lb_admin = new javax.swing.JLabel();
        fondo_admin = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_Reg = new javax.swing.JButton();
        bnt_ingresar_admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_id_admin.setText("Digite ID:");
        getContentPane().add(lb_id_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 219, -1, -1));

        lb_nombre_admin.setText("Digite nombre:");
        getContentPane().add(lb_nombre_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 246, -1, -1));

        txt_id_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_adminActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 216, 83, -1));
        getContentPane().add(txt_nombre_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 243, 83, -1));

        lb_admin.setForeground(new java.awt.Color(0, 153, 51));
        lb_admin.setText("BIENVENIDO ADMINISTRADOR");
        getContentPane().add(lb_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 5, -1, -1));

        fondo_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/admin.jpg"))); // NOI18N
        getContentPane().add(fondo_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 30, -1, 180));

        btn_cerrar.setText("Cerrar");
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 11, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 210));

        jPanel2.setBackground(new java.awt.Color(153, 255, 51));

        btn_Reg.setText("¿No está registrado?, Click aqui");

        bnt_ingresar_admin.setText("Ingresar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Reg)
                    .addComponent(bnt_ingresar_admin))
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnt_ingresar_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_Reg)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 450, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_administrador().setVisible(true);
            }
        });
    }

    
    public JButton getBtn_cerrar() {
        return btn_cerrar;
    }

    public void setBtn_cerrar(JButton btn_cerrar) {
        this.btn_cerrar = btn_cerrar;
    }



    public JButton getBnt_ingresar_admin() {
        return bnt_ingresar_admin;
    }

    public void setBnt_ingresar_admin(JButton bnt_ingresar_admin) {
        this.bnt_ingresar_admin = bnt_ingresar_admin;
    }

    public JLabel getFondo_admin() {
        return fondo_admin;
    }

    public void setFondo_admin(JLabel fondo_admin) {
        this.fondo_admin = fondo_admin;
    }

    public JLabel getLb_admin() {
        return lb_admin;
    }

    public void setLb_admin(JLabel lb_admin) {
        this.lb_admin = lb_admin;
    }

    public JLabel getLb_id_admin() {
        return lb_id_admin;
    }

    public void setLb_id_admin(JLabel lb_id_admin) {
        this.lb_id_admin = lb_id_admin;
    }

    public JLabel getLb_nombre_admin() {
        return lb_nombre_admin;
    }

    public void setLb_nombre_admin(JLabel lb_nombre_admin) {
        this.lb_nombre_admin = lb_nombre_admin;
    }


    public JTextField getTxt_id_admin() {
        return txt_id_admin;
    }

    public void setTxt_id_admin(JTextField txt_id_admin) {
        this.txt_id_admin = txt_id_admin;
    }

    public JTextField getTxt_nombre_admin() {
        return txt_nombre_admin;
    }

    public void setTxt_nombre_admin(JTextField txt_nombre_admin) {
        this.txt_nombre_admin = txt_nombre_admin;
    }



    public JButton getBtn_Reg() {
        return btn_Reg;
    }

    public void setBtn_Reg(JButton btn_Reg) {
        this.btn_Reg = btn_Reg;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_ingresar_admin;
    private javax.swing.JButton btn_Reg;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel fondo_admin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_id_admin;
    private javax.swing.JLabel lb_nombre_admin;
    private javax.swing.JTextField txt_id_admin;
    private javax.swing.JTextField txt_nombre_admin;
    // End of variables declaration//GEN-END:variables
}
