/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author JULIAN
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        lbl_adminsitrador = new javax.swing.JLabel();
        lbl_encargado = new javax.swing.JLabel();
        lbl_cliente = new javax.swing.JLabel();
        btn_admin = new javax.swing.JButton();
        btn_encargado = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setForeground(new java.awt.Color(102, 255, 0));
        titulo.setText("BIENVENIDO SEÑOR USUARIO");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, -1));

        lbl_adminsitrador.setForeground(new java.awt.Color(51, 255, 204));
        lbl_adminsitrador.setText("INGRESAR COMO ADMINISTRADOR: ");
        getContentPane().add(lbl_adminsitrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lbl_encargado.setForeground(new java.awt.Color(51, 255, 204));
        lbl_encargado.setText("INGRESAR COMO ENCARGADO: ");
        getContentPane().add(lbl_encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lbl_cliente.setForeground(new java.awt.Color(102, 255, 204));
        lbl_cliente.setText("INGRESAR/REGISTRAR COMO CLIENTE: ");
        getContentPane().add(lbl_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btn_admin.setText("AQUI");
        getContentPane().add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        btn_encargado.setText("AQUI");
        getContentPane().add(btn_encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        btn_cliente.setText("AQUI");
        getContentPane().add(btn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    public JButton getBtn_salir() {
        return btn_salir;
    }

    public void setBtn_salir(JButton btn_salir) {
        this.btn_salir = btn_salir;
    }

  

    public JButton getBtn_admin() {
        return btn_admin;
    }

    public void setBtn_admin(JButton btn_admin) {
        this.btn_admin = btn_admin;
    }

    public JButton getBtn_cliente() {
        return btn_cliente;
    }

    public void setBtn_cliente(JButton btn_cliente) {
        this.btn_cliente = btn_cliente;
    }

    public JButton getBtn_encargado() {
        return btn_encargado;
    }

    public void setBtn_encargado(JButton btn_encargado) {
        this.btn_encargado = btn_encargado;
    }

    public JLabel getFondo() {
        return fondo;
    }

    public void setFondo(JLabel fondo) {
        this.fondo = fondo;
    }

    public JLabel getLbl_adminsitrador() {
        return lbl_adminsitrador;
    }

    public void setLbl_adminsitrador(JLabel lbl_adminsitrador) {
        this.lbl_adminsitrador = lbl_adminsitrador;
    }

    public JLabel getLbl_cliente() {
        return lbl_cliente;
    }

    public void setLbl_cliente(JLabel lbl_cliente) {
        this.lbl_cliente = lbl_cliente;
    }

    public JLabel getLbl_encargado() {
        return lbl_encargado;
    }

    public void setLbl_encargado(JLabel lbl_encargado) {
        this.lbl_encargado = lbl_encargado;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_encargado;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lbl_adminsitrador;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JLabel lbl_encargado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
