/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author JULIAN
 */
public class Registro_Adim extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Adim
     */
    public Registro_Adim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        FONDO = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        lbl_nom = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        btn_reg = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/admin.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 36, -1, -1));

        TITULO.setBackground(new java.awt.Color(255, 204, 51));
        TITULO.setForeground(new java.awt.Color(51, 255, 153));
        TITULO.setText("REGISTRO DE ADMINISTRADOR");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 16, -1, -1));

        lbl_nom.setText("Nombre:");
        getContentPane().add(lbl_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 276, -1, -1));

        lbl_id.setText("ID:");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 249, -1, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 246, 65, -1));
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 273, 65, -1));

        btn_reg.setText("Registrar");
        getContentPane().add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 272, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_cerrar.setText("Cerrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(btn_cerrar)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cerrar)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Adim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Adim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Adim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Adim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Adim().setVisible(true);
            }
        });
    }

    public JButton getBtn_cerrar() {
        return btn_cerrar;
    }

    public void setBtn_cerrar(JButton btn_cerrar) {
        this.btn_cerrar = btn_cerrar;
    }

    public JLabel getFONDO() {
        return FONDO;
    }

    public void setFONDO(JLabel FONDO) {
        this.FONDO = FONDO;
    }

    public JLabel getTITULO() {
        return TITULO;
    }

    public void setTITULO(JLabel TITULO) {
        this.TITULO = TITULO;
    }

    public JButton getBtn_reg() {
        return btn_reg;
    }

    public void setBtn_reg(JButton btn_reg) {
        this.btn_reg = btn_reg;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JLabel getLbl_id() {
        return lbl_id;
    }

    public void setLbl_id(JLabel lbl_id) {
        this.lbl_id = lbl_id;
    }

    public JLabel getLbl_nom() {
        return lbl_nom;
    }

    public void setLbl_nom(JLabel lbl_nom) {
        this.lbl_nom = lbl_nom;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nom() {
        return txt_nom;
    }

    public void setTxt_nom(JTextField txt_nom) {
        this.txt_nom = txt_nom;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_reg;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nom;
    // End of variables declaration//GEN-END:variables
}
